version: '3.3'

services:
    av_dashboard:
        image: postgres
        container_name: av_dashboard
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgresdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - my_network

volumes:
    postgresdata:

networks:
    my_network:
        driver: bridge
